<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWnF1gh9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWnF1gh9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWnF1gh9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWnF1gh9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWnF1gh9\App_KernelDevDebugContainer([
    'container.build_hash' => 'WnF1gh9',
    'container.build_id' => '2d99f022',
    'container.build_time' => 1681651848,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWnF1gh9');
