<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNVRnl46\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNVRnl46/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNVRnl46.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNVRnl46\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNVRnl46\App_KernelDevDebugContainer([
    'container.build_hash' => 'NVRnl46',
    'container.build_id' => 'c0aabebe',
    'container.build_time' => 1678033109,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNVRnl46');
